sudo: required

language: node_js

branches:
  only:
    - master
    - gh-pages
    - newMaster

before_script:
  - npm i -g gulp
  - npm --version

script: 
  - gulp build

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - ./push.sh
