language: node_js

branches:
  only:
    - master
    - gh-pages

before_script:
  - npm install -g gulp

script:
  - gulp build

node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "iojs"
